sudo: required
services:
  - docker


before_install: 
  - docker build -t soulaimane9js/react-app-dev -f Dockerfile.dev ./client

script:
  - docker run soulaimane9js/react-app-dev npm test -- --coverage


after_success:
  - docker build -t soulaimane9js/react-app-prod ./client
  - docker build -t soulaimane9js/backend-app-prod ./server
  - docker build -t soulaimane9js/worker-prod ./nginx
  - docker build -t soulaimane9js/nginx-prod ./


  - echo wnG52RuKRysBp2T | docker login -u soulaimane9js


  - docker push soulaimane9js/react-app-prod
  - docker push soulaimane9js/backend-app-prod
  - docker push soulaimane9js/worker-prod
  - docker push soulaimane9js/nginx-prod
