name: Course ci-cd



on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker dev
      run: docker build -t soulaimane9js/react-app-dev -f Dockerfile.dev .
      working-directory: ./client

    - name: Run tests
      run: docker run soulaimane9js/react-app-dev npm test -- --coverage
      working-directory: ./client

    - name: Build production frontend
      run: docker build -t soulaimane9js/react-app-prod .
      working-directory: ./client

    - name: Build production backend
      run: docker build -t soulaimane9js/backend-app-prod .
      working-directory: ./server

    - name: Build production worker
      run: docker build -t soulaimane9js/worker-prod .
      working-directory: ./worker

    - name: Build production nginx
      run: docker build -t soulaimane9js/nginx-prod .
      working-directory: ./nginx

    - name: Docker Loging
      uses: docker/login-action@v3
      with:
        username: soulaimane9js
        password: wnG52RuKRysBp2T
            
    - name: Docker push react front end
      run: docker push soulaimane9js/react-app-prod

    - name: Docker push back end
      run: docker push soulaimane9js/backend-app-prod

    - name: Docker push worker
      run: docker push soulaimane9js/worker-prod
      
    - name: Docker push nginx
      run: docker push soulaimane9js/nginx-prod

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAWFWKQPT4QZ4C62MN
        aws-secret-access-key: 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
        aws-region: eu-north-1

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name tryDockerAgain \
          --version-label $GITHUB_SHA \
          --description "GitHub Actions Deployment" \
          --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-424552725753

        aws elasticbeanstalk update-environment \
          --environment-name TryDockerAgain-env \
          --version-label $GITHUB_SHA

        aws elasticbeanstalk wait environment-healthy --environment-name TryDockerAgain-env

      env:
        EB_BUCKET_NAME: elasticbeanstalk-eu-north-1-424552725753
        EB_BUCKET_PATH: docker-multi
        

